import json
import os
from logging_config import log

# env
ENV = os.environ.get("ENVIRONMENT", "PROD")
log.info(f"running in {ENV} environment.")

# read secrets.json
with open("secrets.json", "r") as f:
    SECRETS = json.load(f)

# CONSTANTS
HOST = SECRETS.get('HOST', '0.0.0.0')
PORT = SECRETS.get('PORT', 8000)
DEBUG = False if ENV == 'PROD' else True
DATABASE_NAME = SECRETS['DATABASE_NAME']
DATABASE_MAX_POOL_SIZE = SECRETS['DATABASE_MAX_POOL_SIZE']
DATABASE_URL = SECRETS['DATABASE_URL']
DATABASE_PORT = SECRETS['DATABASE_PORT']
DATABASE_PASSWORD = SECRETS['DATABASE_PASSWORD']
DATABASE_USER = SECRETS['DATABASE_USER']
JWT_TOKEN_EXPIRY_IN_DAYS = SECRETS['JWT_TOKEN_EXPIRY_IN_DAYS']
JWT_SECRET_KEY = SECRETS['JWT_SECRET_KEY']
JWT_ALGORITHM = SECRETS['JWT_ALGORITHM']
IMAGES_UPLOAD_FOLDER = SECRETS['IMAGES_UPLOAD_FOLDER']
