import json
import os
from logging_config import log

# env
ENV = os.environ.get("ENVIRONMENT", "DEV")
log.info(f"running in {ENV} environment.")

# read secrets.json
with open("secrets.json", "r") as f:
    SECRETS = json.load(f)

# CONSTANTS
HOST = SECRETS.get('HOST', '0.0.0.0')
PORT = SECRETS.get('PORT', 8000)
PROTOCOL = SECRETS.get('PROTOCOL', 'http') # possible values: http or https
BASE_URL = f"{PROTOCOL}://{HOST}:{PORT}"
DEBUG = False if ENV == 'PROD' else True
DATABASE_NAME = SECRETS['DATABASE_NAME']
DATABASE_MAX_POOL_SIZE = SECRETS['DATABASE_MAX_POOL_SIZE']
DATABASE_URL = SECRETS['DATABASE_URL']
DATABASE_PORT = SECRETS['DATABASE_PORT']
DATABASE_PASSWORD = SECRETS['DATABASE_PASSWORD']
DATABASE_USER = SECRETS['DATABASE_USER']
DATABASE_REPLICA_SET_NAME = SECRETS.get('DATABASE_REPLICA_SET_NAME', "rs0")
JWT_TOKEN_EXPIRY_IN_DAYS = SECRETS['JWT_TOKEN_EXPIRY_IN_DAYS']
JWT_SECRET_KEY = SECRETS['JWT_SECRET_KEY']
JWT_ALGORITHM = SECRETS['JWT_ALGORITHM']
IMAGES_UPLOAD_FOLDER = SECRETS['IMAGES_UPLOAD_FOLDER']
TAP_PAYMENT_API_URL = SECRETS['TAP_PAYMENT_API_URL']
TAP_PAYMENT_API_KEY = SECRETS['TAP_PAYMENT_API_KEY']
