from enum import Enum


class AvailableService(Enum):
    INDIVIDUAL_TRAINING_SESSIONS = "INDIVIDUAL_TRAINING_SESSIONS"
    GROUP_TRAINING_SESSIONS ="GROUP_TRAINING_SESSIONS"
    ONLINE_COACHING = "ONLINE_COACHING"
    COMPETITION_PREPARATION = "COMPETITION_PREPARATION"