name: Build and Deploy to Khayyal Dev Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: prints hello world
        run: echo "Hello World from Build"
  deploy:
    needs: build
    runs-on: ubuntu-latest


    steps:
      - name: prints hello world
        run: echo "Hello World from deploy"
